// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SentimentAnalysisApi.Data;

#nullable disable

namespace SentimentAnalysisApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241007081924_InitialCreateOne")]
    partial class InitialCreateOne
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("SentimentAnalysisApi.Models.SentimentAnalysisModel", b =>
                {
                    b.Property<int>("SentimentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Sentiment")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("SentimentId");

                    b.ToTable("SentimentAnalyses");
                });
#pragma warning restore 612, 618
        }
    }
}
